export const WORKFLOW_MODULE_OPTIONS = 'WORKFLOW_MODULE_OPTIONS';
export const WORKFLOW_DB_ADAPTER = 'WORKFLOW_DB_ADAPTER';
export const WORKFLOW_ENGINE = 'WORKFLOW_ENGINE';

export const DEFAULT_CRON_EXPRESSION = '*/60 * * * * *';
export const DEFAULT_TIMEOUT_EVENT = 'TIMEOUT';
export const DEFAULT_MAX_DEPTH = 100;

export const WORKFLOW_ENTITY_METADATA = 'WORKFLOW_ENTITY_METADATA';
